
title: Tran Quang Hung
email:
description: >-
  Tran Quang Hung's academic homepage and blog.

theme: minimal-mistakes-jekyll
minimal_mistake_skin: dirt
search: true
markdown: kramdown
permalink: /:title/
paginate: 10
paginate_path: /page:num/

include:
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache

author:
  name: "Tran Quang Hung"
  avatar: "/assets/images/avatar.jpg"
  bio: ""
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://tranquanghung.me"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://qh-ghp.github.io"

footer:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://tranquanghung.me"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://qh-ghp.github.io"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
