
title: Quang Hung Tran
email:
description: >-
  Tran Quang Hung's academic homepage and blog.

theme: minimal-mistakes-jekyll

# minimal_mistakes_skin: _sunrise
search: true
markdown: kramdown
breadcrumbs: true

sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

include:
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache
  - jekyll-paginate-v2

author:
  name: "Tran Quang Hung"
  avatar: "/assets/images/avatar.jpg"
  bio: ""
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://tranquanghung.me"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://qh-ghp.github.io"

footer:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://tranquanghung.me"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://qh-ghp.github.io"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      permalink: /blogs/:title/

  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

pagination:
  enabled: true

collections:
  - problems
